(cl:in-package robot_abu-srv)
(cl:export '(MISSION_COUNTER-VAL
          MISSION_COUNTER
          ASK-VAL
          ASK
          ARG0-VAL
          ARG0
          ARG1-VAL
          ARG1
          ARG2-VAL
          ARG2
          ARG3-VAL
          ARG3
          ARG4-VAL
          ARG4
          ARG5-VAL
          ARG5
          ARG6-VAL
          ARG6
          ARG7-VAL
          ARG7
          ARG8-VAL
          ARG8
          ARG9-VAL
          ARG9
          ARG10-VAL
          ARG10
          ARG11-VAL
          ARG11
          ARG12-VAL
          ARG12
          ARG13-VAL
          ARG13
          ARG14-VAL
          ARG14
          ARG15-VAL
          ARG15
          ARG16-VAL
          ARG16
          ARG17-VAL
          ARG17
          ARG18-VAL
          ARG18
          ARG19-VAL
          ARG19
          ARG20-VAL
          ARG20
          ARG21-VAL
          ARG21
          ARG22-VAL
          ARG22
          ARG23-VAL
          ARG23
          ARG24-VAL
          ARG24
          ARG25-VAL
          ARG25
))