// Generated by gencpp from file robot_abu/commands_srv.msg
// DO NOT EDIT!


#ifndef ROBOT_ABU_MESSAGE_COMMANDS_SRV_H
#define ROBOT_ABU_MESSAGE_COMMANDS_SRV_H

#include <ros/service_traits.h>


#include <robot_abu/commands_srvRequest.h>
#include <robot_abu/commands_srvResponse.h>


namespace robot_abu
{

struct commands_srv
{

typedef commands_srvRequest Request;
typedef commands_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct commands_srv
} // namespace robot_abu


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_abu::commands_srv > {
  static const char* value()
  {
    return "e26ed80b052f88197b0c98586e1a7d10";
  }

  static const char* value(const ::robot_abu::commands_srv&) { return value(); }
};

template<>
struct DataType< ::robot_abu::commands_srv > {
  static const char* value()
  {
    return "robot_abu/commands_srv";
  }

  static const char* value(const ::robot_abu::commands_srv&) { return value(); }
};


// service_traits::MD5Sum< ::robot_abu::commands_srvRequest> should match
// service_traits::MD5Sum< ::robot_abu::commands_srv >
template<>
struct MD5Sum< ::robot_abu::commands_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_abu::commands_srv >::value();
  }
  static const char* value(const ::robot_abu::commands_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_abu::commands_srvRequest> should match
// service_traits::DataType< ::robot_abu::commands_srv >
template<>
struct DataType< ::robot_abu::commands_srvRequest>
{
  static const char* value()
  {
    return DataType< ::robot_abu::commands_srv >::value();
  }
  static const char* value(const ::robot_abu::commands_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_abu::commands_srvResponse> should match
// service_traits::MD5Sum< ::robot_abu::commands_srv >
template<>
struct MD5Sum< ::robot_abu::commands_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_abu::commands_srv >::value();
  }
  static const char* value(const ::robot_abu::commands_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_abu::commands_srvResponse> should match
// service_traits::DataType< ::robot_abu::commands_srv >
template<>
struct DataType< ::robot_abu::commands_srvResponse>
{
  static const char* value()
  {
    return DataType< ::robot_abu::commands_srv >::value();
  }
  static const char* value(const ::robot_abu::commands_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_ABU_MESSAGE_COMMANDS_SRV_H
