(cl:in-package robot_abu-msg)
(cl:export '(GLOBAL_POS_X-VAL
          GLOBAL_POS_X
          GLOBAL_POS_Y-VAL
          GLOBAL_POS_Y
          SLIDER-VAL
          SLIDER
          ROT-VAL
          ROT
          ROT_DEG-VAL
          ROT_DEG
          ENGSEL-VAL
          ENGSEL
          GYRO-VAL
          GYRO
          GYRO_FULL-VAL
          GYRO_FULL
          CAPIT-VAL
          CAPIT
          SICK_KIRI-VAL
          SICK_KIRI
          SICK_DEPAN-VAL
          SICK_DEPAN
          SICK_BELAKANG-VAL
          SICK_BELAKANG
          RESET-VAL
          RESET
          STM_RESETED-VAL
          STM_RESETED
          TILT_KIRI-VAL
          TILT_KIRI
          TILT_KANAN-VAL
          TILT_KANAN
))