# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ros_er/commands_srvRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class commands_srvRequest(genpy.Message):
  _md5sum = "01a849e291c6457a0413eaabe3e816d4"
  _type = "ros_er/commands_srvRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int8 mission_counter
int16 ask
"""
  __slots__ = ['mission_counter','ask']
  _slot_types = ['int8','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       mission_counter,ask

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(commands_srvRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.mission_counter is None:
        self.mission_counter = 0
      if self.ask is None:
        self.ask = 0
    else:
      self.mission_counter = 0
      self.ask = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_bh().pack(_x.mission_counter, _x.ask))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.mission_counter, _x.ask,) = _get_struct_bh().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_bh().pack(_x.mission_counter, _x.ask))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.mission_counter, _x.ask,) = _get_struct_bh().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_bh = None
def _get_struct_bh():
    global _struct_bh
    if _struct_bh is None:
        _struct_bh = struct.Struct("<bh")
    return _struct_bh
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ros_er/commands_srvResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class commands_srvResponse(genpy.Message):
  _md5sum = "7a06f282c5865fe19b3c0085420e8073"
  _type = "ros_er/commands_srvResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 arg0
int32 arg1
int32 arg2
int32 arg3
int32 arg4
int32 arg5
int32 arg6
int32 arg7
int32 arg8
int32 arg9
int32 arg10
int32 arg11
int32 arg12
int32 arg13
int32 arg14
int32 arg15
int32 arg16
int32 arg17
int32 arg18
int32 arg19
int32 arg20
int32 arg21
int32 arg22
int32 arg23
int32 arg24
int32 arg25
#int32[] args
"""
  __slots__ = ['arg0','arg1','arg2','arg3','arg4','arg5','arg6','arg7','arg8','arg9','arg10','arg11','arg12','arg13','arg14','arg15','arg16','arg17','arg18','arg19','arg20','arg21','arg22','arg23','arg24','arg25']
  _slot_types = ['int32','int32','int32','int32','int32','int32','int32','int32','int32','int32','int32','int32','int32','int32','int32','int32','int32','int32','int32','int32','int32','int32','int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       arg0,arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10,arg11,arg12,arg13,arg14,arg15,arg16,arg17,arg18,arg19,arg20,arg21,arg22,arg23,arg24,arg25

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(commands_srvResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.arg0 is None:
        self.arg0 = 0
      if self.arg1 is None:
        self.arg1 = 0
      if self.arg2 is None:
        self.arg2 = 0
      if self.arg3 is None:
        self.arg3 = 0
      if self.arg4 is None:
        self.arg4 = 0
      if self.arg5 is None:
        self.arg5 = 0
      if self.arg6 is None:
        self.arg6 = 0
      if self.arg7 is None:
        self.arg7 = 0
      if self.arg8 is None:
        self.arg8 = 0
      if self.arg9 is None:
        self.arg9 = 0
      if self.arg10 is None:
        self.arg10 = 0
      if self.arg11 is None:
        self.arg11 = 0
      if self.arg12 is None:
        self.arg12 = 0
      if self.arg13 is None:
        self.arg13 = 0
      if self.arg14 is None:
        self.arg14 = 0
      if self.arg15 is None:
        self.arg15 = 0
      if self.arg16 is None:
        self.arg16 = 0
      if self.arg17 is None:
        self.arg17 = 0
      if self.arg18 is None:
        self.arg18 = 0
      if self.arg19 is None:
        self.arg19 = 0
      if self.arg20 is None:
        self.arg20 = 0
      if self.arg21 is None:
        self.arg21 = 0
      if self.arg22 is None:
        self.arg22 = 0
      if self.arg23 is None:
        self.arg23 = 0
      if self.arg24 is None:
        self.arg24 = 0
      if self.arg25 is None:
        self.arg25 = 0
    else:
      self.arg0 = 0
      self.arg1 = 0
      self.arg2 = 0
      self.arg3 = 0
      self.arg4 = 0
      self.arg5 = 0
      self.arg6 = 0
      self.arg7 = 0
      self.arg8 = 0
      self.arg9 = 0
      self.arg10 = 0
      self.arg11 = 0
      self.arg12 = 0
      self.arg13 = 0
      self.arg14 = 0
      self.arg15 = 0
      self.arg16 = 0
      self.arg17 = 0
      self.arg18 = 0
      self.arg19 = 0
      self.arg20 = 0
      self.arg21 = 0
      self.arg22 = 0
      self.arg23 = 0
      self.arg24 = 0
      self.arg25 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_26i().pack(_x.arg0, _x.arg1, _x.arg2, _x.arg3, _x.arg4, _x.arg5, _x.arg6, _x.arg7, _x.arg8, _x.arg9, _x.arg10, _x.arg11, _x.arg12, _x.arg13, _x.arg14, _x.arg15, _x.arg16, _x.arg17, _x.arg18, _x.arg19, _x.arg20, _x.arg21, _x.arg22, _x.arg23, _x.arg24, _x.arg25))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 104
      (_x.arg0, _x.arg1, _x.arg2, _x.arg3, _x.arg4, _x.arg5, _x.arg6, _x.arg7, _x.arg8, _x.arg9, _x.arg10, _x.arg11, _x.arg12, _x.arg13, _x.arg14, _x.arg15, _x.arg16, _x.arg17, _x.arg18, _x.arg19, _x.arg20, _x.arg21, _x.arg22, _x.arg23, _x.arg24, _x.arg25,) = _get_struct_26i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_26i().pack(_x.arg0, _x.arg1, _x.arg2, _x.arg3, _x.arg4, _x.arg5, _x.arg6, _x.arg7, _x.arg8, _x.arg9, _x.arg10, _x.arg11, _x.arg12, _x.arg13, _x.arg14, _x.arg15, _x.arg16, _x.arg17, _x.arg18, _x.arg19, _x.arg20, _x.arg21, _x.arg22, _x.arg23, _x.arg24, _x.arg25))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 104
      (_x.arg0, _x.arg1, _x.arg2, _x.arg3, _x.arg4, _x.arg5, _x.arg6, _x.arg7, _x.arg8, _x.arg9, _x.arg10, _x.arg11, _x.arg12, _x.arg13, _x.arg14, _x.arg15, _x.arg16, _x.arg17, _x.arg18, _x.arg19, _x.arg20, _x.arg21, _x.arg22, _x.arg23, _x.arg24, _x.arg25,) = _get_struct_26i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_26i = None
def _get_struct_26i():
    global _struct_26i
    if _struct_26i is None:
        _struct_26i = struct.Struct("<26i")
    return _struct_26i
class commands_srv(object):
  _type          = 'ros_er/commands_srv'
  _md5sum = 'e26ed80b052f88197b0c98586e1a7d10'
  _request_class  = commands_srvRequest
  _response_class = commands_srvResponse
