// Generated by gencpp from file ros_er/commands_srv.msg
// DO NOT EDIT!


#ifndef ROS_ER_MESSAGE_COMMANDS_SRV_H
#define ROS_ER_MESSAGE_COMMANDS_SRV_H

#include <ros/service_traits.h>


#include <ros_er/commands_srvRequest.h>
#include <ros_er/commands_srvResponse.h>


namespace ros_er
{

struct commands_srv
{

typedef commands_srvRequest Request;
typedef commands_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct commands_srv
} // namespace ros_er


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_er::commands_srv > {
  static const char* value()
  {
    return "e26ed80b052f88197b0c98586e1a7d10";
  }

  static const char* value(const ::ros_er::commands_srv&) { return value(); }
};

template<>
struct DataType< ::ros_er::commands_srv > {
  static const char* value()
  {
    return "ros_er/commands_srv";
  }

  static const char* value(const ::ros_er::commands_srv&) { return value(); }
};


// service_traits::MD5Sum< ::ros_er::commands_srvRequest> should match
// service_traits::MD5Sum< ::ros_er::commands_srv >
template<>
struct MD5Sum< ::ros_er::commands_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_er::commands_srv >::value();
  }
  static const char* value(const ::ros_er::commands_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_er::commands_srvRequest> should match
// service_traits::DataType< ::ros_er::commands_srv >
template<>
struct DataType< ::ros_er::commands_srvRequest>
{
  static const char* value()
  {
    return DataType< ::ros_er::commands_srv >::value();
  }
  static const char* value(const ::ros_er::commands_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_er::commands_srvResponse> should match
// service_traits::MD5Sum< ::ros_er::commands_srv >
template<>
struct MD5Sum< ::ros_er::commands_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_er::commands_srv >::value();
  }
  static const char* value(const ::ros_er::commands_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_er::commands_srvResponse> should match
// service_traits::DataType< ::ros_er::commands_srv >
template<>
struct DataType< ::ros_er::commands_srvResponse>
{
  static const char* value()
  {
    return DataType< ::ros_er::commands_srv >::value();
  }
  static const char* value(const ::ros_er::commands_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_ER_MESSAGE_COMMANDS_SRV_H
