(cl:in-package ros_er-msg)
(cl:export '(SPEED_X-VAL
          SPEED_X
          SPEED_Y-VAL
          SPEED_Y
          SPEED_Z-VAL
          SPEED_Z
          TARGET_SLIDER-VAL
          TARGET_SLIDER
          SPEED_SLIDER-VAL
          SPEED_SLIDER
          TARGET_ROT-VAL
          TARGET_ROT
          SPEED_ROT-VAL
          SPEED_ROT
          TARGET_CAPIT-VAL
          TARGET_CAPIT
          SPEED_CAPIT-VAL
          SPEED_CAPIT
          TARGET_ENGSEL-VAL
          TARGET_ENGSEL
          BIT_PNEUMATIK-VAL
          BIT_PNEUMATIK
          STATUS_ROBOT-VAL
          STATUS_ROBOT
          RESET_ENC-VAL
          RESET_ENC
          RESET_GPOS_X-VAL
          RESET_GPOS_X
          RESET_GPOS_Y-VAL
          RESET_GPOS_Y
          RESET_GYRO_VAL-VAL
          RESET_GYRO_VAL
          BUZZER-VAL
          BUZZER
          POS_HEAD-VAL
          POS_HEAD
          ACC_X-VAL
          ACC_X
          ACC_Y-VAL
          ACC_Y
          ACC_Z-VAL
          ACC_Z
          TILT_KIRI-VAL
          TILT_KIRI
          TILT_KANAN-VAL
          TILT_KANAN
          TARGET_CARRY-VAL
          TARGET_CARRY
          SPEED_CARRY-VAL
          SPEED_CARRY
))