(cl:in-package ros_er-msg)
(cl:export '(SPEED_X-VAL
          SPEED_X
          SPEED_Y-VAL
          SPEED_Y
          SPEED_Z-VAL
          SPEED_Z
          ODOM_X-VAL
          ODOM_X
          ODOM_Y-VAL
          ODOM_Y
          GYRO_FULL-VAL
          GYRO_FULL
          TARGET_SPEED_X-VAL
          TARGET_SPEED_X
          TARGET_SPEED_Y-VAL
          TARGET_SPEED_Y
          TARGET_SPEED_Z-VAL
          TARGET_SPEED_Z
          LASER-VAL
          LASER
          LASER_HPF-VAL
          LASER_HPF
          COMMAND_TYPE-VAL
          COMMAND_TYPE
          M_CTR-VAL
          M_CTR
          TIME_STAMP-VAL
          TIME_STAMP
))